### ISSUE TITLE
Type of property DocumentMetadataConfigurations incorrect, causing validation errors

### ISSUE THREAD

**Issue by cogwirrel** [aws-cloudformation/aws-cloudformation-resource-providers-kendra#77]
Hi,

I've been using CDK to define a kendra index, and am trying to define custom attributes in the document metadata.

```js
new kendra.CfnIndex(this, 'MyIndex', {
    edition: 'DEVELOPER_EDITION',
    name: `${props.stage}-MyIndex`,
    roleArn: kendraIndexRole.roleArn,
    documentMetadataConfigurations: {
        documentMetadataConfigurationList: [
            {
                name: 'myAttribute',
                type: 'STRING_VALUE',
                search: {
                    displayable: true,
                    searchable: false,
                    sortable: false,
                    facetable: false,
                },
            },
        ],
    },
});
```

When I synth and deploy, I get an error:

```
5:35:40 PM | UPDATE_FAILED        | AWS::Kendra::Index | KendraWebCrawlerIndex
Model validation failed (#/DocumentMetadataConfigurations: expected type: JSONArray, found: JSONObject)
```

However this doesn't match the cloudformation documentation, which states that `DocumentMetadataConfigurations` is an object with a single property `DocumentMetadataConfigurationsList`.

See: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-kendra-index.html#cfn-kendra-index-documentmetadataconfigurations and https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-kendra-index-documentmetadataconfigurationlist.html

It's also the case with the generated cdk `CfnIndex` construct.

I'm not super familiar with how cloudformation works, but I believe the problem is that the top level property `DocumentMetadataConfigurations` is defined as:

```json
    "DocumentMetadataConfigurations": {
      "description": "Document metadata configurations",
      "$ref": "#/definitions/DocumentMetadataConfigurationList"
    },
```

And the `DocumentMetadataConfigurationList` is [defined as an array](https://github.com/cogwirrel/aws-cloudformation-resource-providers-kendra/blob/75bb7d9b926861feec629be00bb24d7011a0dc43/aws-kendra-index/aws-kendra-index.json#L169-L175) rather than an object with a single `DocumentMetadataConfigurationsList` property.

```json
    "DocumentMetadataConfigurationList": {
      "type": "array",
      "maxItems": 500,
      "items": {
        "$ref": "#/definitions/DocumentMetadataConfiguration"
      }
    },
```

Thanks,
Jack

**Comment by cogwirrel** [comment]
Raised an issue for aws-cdk :)

https://github.com/aws/aws-cdk/issues/11402

**Comment by jregistr** [comment]
Hi @cogwirrel, do I understand correctly by the resolution of https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-kendra/pull/79 that this is no longer an issue? Is this okay to close?

**Comment by cogwirrel** [comment]
Yes that's right! All fixed :)

**Comment by jregistr** [comment]
> Yes that's right! All fixed :)

Amazing!
